import os
import requests
from fastapi import FastAPI, Request, BackgroundTasks
import uvicorn
from dotenv import load_dotenv
from openai import OpenAI

# Load keys
load_dotenv()
GIT_TOKEN = os.getenv("GITHUB_TOKEN")
GROQ_KEY = os.getenv("OPENAI_API_KEY")

app = FastAPI()

# 1. AI Logic (Improved Prompt for better UI/UX)
def get_ai_review(diff):
    client = OpenAI(api_key=GROQ_KEY, base_url="https://api.groq.com/openai/v1")
    
    # This is the "Secret Sauce" that makes your bot look professional
    prompt = f"""
    You are a Senior Staff Engineer. Review the following code changes (diff):
    {diff}

    Format your response exactly like this:
    
    # 🤖 AI Code Review Summary
    **Overall Health Score: [X/10]**

    ### 🚩 Critical Issues (Bugs & Security)
    - **Issue:** [Description]
    - **Risk:** [Why it's dangerous]
    - **Fix:** [One-line fix]

    ### 💡 Suggestions for Improvement
    - [Mention code smell or performance issues]

    ---
    *Generated by ReviewPulse AI Agent*
    """
    
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

# 2. GitHub Logic
def get_diff(repo, pr_no):
    url = f"https://api.github.com/repos/{repo}/pulls/{pr_no}"
    headers = {"Authorization": f"token {GIT_TOKEN}", "Accept": "application/vnd.github.v3.diff"}
    return requests.get(url, headers=headers).text

def post_comment(repo, pr_no, text):
    url = f"https://api.github.com/repos/{repo}/issues/{pr_no}/comments"
    headers = {"Authorization": f"token {GIT_TOKEN}"}
    requests.post(url, json={"body": text}, headers=headers)

# 3. Server Logic
@app.post("/webhook")
async def webhook(request: Request, bg: BackgroundTasks):
    data = await request.json()
    if "pull_request" in data and data["action"] in ["opened", "synchronize"]:
        repo = data["repository"]["full_name"]
        pr_no = data["number"]
        print(f"🚀 Detected PR #{pr_no}. Starting AI Review...")
        bg.add_task(process, repo, pr_no)
    return {"ok": True}

def process(repo, pr_no):
    try:
        print("📥 Fetching code...")
        diff = get_diff(repo, pr_no)
        print("🤖 AI is analyzing...")
        review = get_ai_review(diff)
        print("📤 Sending review to GitHub...")
        post_comment(repo, pr_no, review) # Note: review already has the header
        print("✅ DONE! Check GitHub!")
    except Exception as e:
        print(f"❌ CRASHED: {e}")

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)